#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 23 15:22:39 2018
move all images in folds including subfolds to a certain fold
@author: dy
"""

import os  
import shutil  
path = '/home/dy/dy/smart_design/20180521/mouse'      ####   headset   handband   watch   VR
new_path = '/home/dy/dy/smart_design/cluster_0521/mouse'  

isExists=os.path.exists(new_path)
if not isExists:
    os.makedirs(new_path)

for root, dirs, files in os.walk(path):  
    if len(dirs) == 0:  
        for i in range(len(files)):  
            if files[i][-3:] == 'jpg':  
                file_path = root+'/'+files[i]  
                new_file_path = new_path+ '/'+ files[i]  
#                shutil.move(file_path,new_file_path)
                shutil.copy(file_path,new_file_path)